import * as JobStore from "../../src/JobStore.ts"
import { PgClient } from "@effect/sql-pg"
import { Effect, Layer, Redacted } from "effect"
import * as net from "node:net"
import { DrizzleJobStore, mqJobAttempts, mqJobs, mqQueueControl, mqSchedules } from "../../src/drizzle/index.ts"

export const pgUrl = process.env.EFFECT_MQ_PG_URL ??
  "postgres://postgres:postgres@localhost:5433/effect_mq_test"

/** True when the test Postgres (docker compose) is reachable. */
export const pgAvailable = (): Promise<boolean> => {
  const { hostname, port } = new URL(pgUrl)
  return new Promise((resolve) => {
    const socket = net.connect({ host: hostname, port: Number(port || 5432), timeout: 500 })
    socket.once("connect", () => {
      socket.destroy()
      resolve(true)
    })
    socket.once("error", () => resolve(false))
    socket.once("timeout", () => {
      socket.destroy()
      resolve(false)
    })
  })
}

export const pgClientLive = (): Layer.Layer<PgClient.PgClient> =>
  PgClient.layer({ url: Redacted.make(pgUrl), maxConnections: 4 }).pipe(Layer.orDie)

/**
 * DDL matching the schema factories exactly (the drift test keeps them
 * honest). Real applications get this from drizzle-kit migrations instead.
 */
export const createTablesSql = (
  jobs: string,
  attempts: string,
  schedules: string,
  queues: string
): ReadonlyArray<string> => [
  `CREATE TABLE "${jobs}" (
    id text PRIMARY KEY,
    name text NOT NULL,
    queue text NOT NULL,
    state text NOT NULL,
    priority integer NOT NULL DEFAULT 0,
    seq bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    payload jsonb,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    attempts_max integer NOT NULL,
    attempts_made integer NOT NULL DEFAULT 0,
    stalled_count integer NOT NULL DEFAULT 0,
    backoff jsonb,
    keep jsonb,
    timeout_ms bigint,
    cancel_requested boolean NOT NULL DEFAULT false,
    run_at timestamptz NOT NULL,
    enqueued_at timestamptz NOT NULL,
    processed_at timestamptz,
    finished_at timestamptz,
    exit jsonb,
    failed_reason text,
    lock_token text,
    lock_expires_at timestamptz
  )`,
  `CREATE INDEX "${jobs}_ready_idx" ON "${jobs}" (queue, priority DESC, seq ASC) WHERE state = 'waiting'`,
  `CREATE INDEX "${jobs}_delayed_idx" ON "${jobs}" (queue, run_at) WHERE state = 'delayed'`,
  `CREATE INDEX "${jobs}_active_idx" ON "${jobs}" (lock_expires_at) WHERE state = 'active'`,
  `CREATE INDEX "${jobs}_history_idx" ON "${jobs}" (name, state, finished_at)`,
  `CREATE INDEX "${jobs}_listing_idx" ON "${jobs}" (enqueued_at DESC, id DESC)`,
  `CREATE INDEX "${jobs}_metadata_idx" ON "${jobs}" USING gin (metadata jsonb_path_ops)`,
  `CREATE TABLE "${attempts}" (
    job_id text NOT NULL REFERENCES "${jobs}" (id) ON DELETE CASCADE,
    attempt integer NOT NULL,
    outcome text NOT NULL,
    started_at timestamptz,
    finished_at timestamptz NOT NULL,
    exit jsonb,
    PRIMARY KEY (job_id, attempt)
  )`,
  `CREATE TABLE "${schedules}" (
    key text PRIMARY KEY,
    job_name text NOT NULL,
    queue text NOT NULL,
    cron text,
    tz text,
    every_ms bigint,
    payload jsonb,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    priority integer NOT NULL DEFAULT 0,
    attempts_max integer NOT NULL,
    backoff jsonb,
    keep jsonb,
    timeout_ms bigint,
    next_run_at timestamptz NOT NULL
  )`,
  `CREATE INDEX "${schedules}_due_idx" ON "${schedules}" (next_run_at)`,
  `CREATE TABLE "${queues}" (
    queue text PRIMARY KEY,
    paused boolean NOT NULL DEFAULT false
  )`
]

let tableCounter = 0
export const freshTableNames = () => {
  const suffix = `${Date.now().toString(36)}_${++tableCounter}_${Math.random().toString(36).slice(2, 6)}`
  return {
    jobs: `mq_jobs_${suffix}`,
    attempts: `mq_att_${suffix}`,
    schedules: `mq_sched_${suffix}`,
    queues: `mq_q_${suffix}`
  }
}

/**
 * A fresh Postgres-backed store: unique tables created on build, dropped on
 * scope close. What real apps do via drizzle-kit, compressed for tests.
 */
export const freshStoreEffect = Effect.gen(function*() {
  const client = yield* PgClient.PgClient
  const names = freshTableNames()
  const jobs = mqJobs(names.jobs)
  const attempts = mqJobAttempts(jobs, names.attempts)
  const schedules = mqSchedules(names.schedules)
  const queues = mqQueueControl(names.queues)
  for (const statement of createTablesSql(names.jobs, names.attempts, names.schedules, names.queues)) {
    yield* client.unsafe(statement)
  }
  yield* Effect.addFinalizer(() =>
    client.unsafe(
      `DROP TABLE IF EXISTS "${names.attempts}", "${names.jobs}", "${names.schedules}", "${names.queues}" CASCADE`
    ).pipe(Effect.ignore)
  )
  const store = yield* DrizzleJobStore.make({ jobs, attempts, schedules, queues })
  return { store, jobs, attempts, schedules, queues, names }
}).pipe(Effect.orDie)

export const freshStoreLayer = (): Layer.Layer<JobStore.JobStore> =>
  Layer.effect(JobStore.JobStore, Effect.map(freshStoreEffect, ({ store }) => store)).pipe(
    Layer.provide(pgClientLive())
  )
